### PR TITLE
add ng docs

### PR DESCRIPTION
**Pull request by DrMabuse23**
add ng docs as gulp task

### CODE REVIEW

**Comment by gruppjo** [comment]
outdated

**Comment by anasmithiam** [comment]
Any plans to add some documentation tool to the generator? ngDocs, Docular, angular-jsdoc, dgeni..? Thanks!

**Comment by gruppjo** [comment]
Hi @anasmithiam, right now it's not a priority. In our opinion there's more urgent things on the way: testing, cordova update, tutorials, cordova hooks and other features to make your life easier. However if you want to get this feature I'll be happy to review your PR!

**Comment by anasmithiam** [comment]
Thank you! @DrMabuse23, have you end up with this PR? Can i review it and may be continue it? regards

**Comment by gruppjo** [comment]
@anasmithiam I'd recommend you simply start a new PR, this one's very old and is based on a code base that's outdated.

**Comment by DrMabuse23** [comment]
@anasmithian i can check it out next days if you need it fast check out my fork

**Comment by anasmithiam** [comment]
@DrMabuse23 ok thanks!

**Comment by LunarDevelopment** [comment]
I'll just leave this here as a possible integration for docs. 

https://github.com/nikhilmodak/gulp-ngdocs

the only addition would be auto generating comment blocks in top of file similar to below rather than have to write them ourselves : 

```javascript 
/**
 * @ngdoc directive
 * @name rfx.directive:rAutogrow
 * @element textarea
 * @function
 *
 * @description
 * Resize textarea automatically to the size of its text content.
 *
 * **Note:** ie<9 needs pollyfill for window.getComputedStyle
 *
 * @example
   <example module="rfx">
     <file name="index.html">
         <textarea ng-model="text"rx-autogrow class="input-block-level"></textarea>
         <pre>{{text}}</pre>
     </file>
   </example>
 */
angular.module('rfx', []).directive('rAutogrow', function() {
  //some nice code
});
```

**Pull request closed without merging**
